lang: en-US
title: Hire a Full-Stack Web & Mobile Software Developer
logo: "/images/logo.jpg"
description: > # remove </br> elements if line breaks are not needed
  Full-Stack Web & Mobile Developer with 9+ years of experience with modern technologies such as Angular and JavaScript
  </br></br>
  Specialized in the M.E.A.N Stack and Flutter
  </br></br>
  <a href="https://www.linkedin.com/in/algife/" class="btn btn-primary">LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: G-4JDY32BRGF
